// POST
export const UPLOAD_ATTACHMENTS = 'UPLOAD_ATTACHMENTS'
export const UPLOAD_ATTACHMENTS_SUCCESS = 'UPLOAD_ATTACHMENTS_SUCCESS'
export const UPLOAD_ATTACHMENTS_ERROR = 'UPLOAD_ATTACHMENTS_ERROR'


// GET
export const GET_ATTACHMENTS = 'GET_ATTACHMENTS'
export const GET_ATTACHMENTS_SUCCESS = 'GET_ATTACHMENTS_SUCCESS'
export const GET_ATTACHMENTS_ERROR = 'GET_ATTACHMENTS_ERROR'


// DELETE
export const DELETE_ATTACHMENTS = 'DELETE_ATTACHMENTS'
export const DELETE_ATTACHMENTS_SUCCESS = 'DELETE_ATTACHMENTS_SUCCESS'
export const DELETE_ATTACHMENTS_ERROR = 'DELETE_ATTACHMENTS_ERROR'
