//List
export const GET_LIST_TASKS = 'GET_LIST_TASKS'
export const GET_LIST_TASKS_SUCCESS = 'GET_LIST_TASKS_SUCCESS'
export const GET_LIST_TASKS_ERROR = 'CREATE_LIST_ERROR';

//Create
export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

//Edit
export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';

//Delete
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

//Update Status
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK';
export const UPDATE_STATUS_TASK_SUCCESS = 'UPDATE_STATUS_TASK_SUCCESS';
export const UPDATE_STATUS_TASK_ERROR = 'UPDATE_STATUS_TASK_ERROR';

//aux
export const INSERT_TASK = 'INSERT_TASK';